name: Wiki Sync (Manual)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Additional steps to generate documentation in "docs/wiki" directory
      - name: Upload docs/wiki to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "docs/wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}